#! /bin/sh

sxhkd &
polybar example &
wmname LG3D &
Telegram/Telegram &
dropbox start &
#slack &
#teams &
feh --randomize --bg-max ~/Desktop/wallpapers/* &

bspc monitor LVDS-1 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 0  
#bspc monitor DP-2 -d 1 2 3 4 5 6  
#bspc monitor VGA-1 -d 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#xrandr --output LVDS-1 --off && sleep 5 && xrandr --output DP-2 --primary --mode 2560x1440 --rate 60.0 --rotate normal --output VGA-1 --mode 1280x1024 --rate 60.0 --rotate normal --right-of DP-2


